
module.exports.TypeformToWordPressMap = {
  '9k5fYUBAnLyl': 'title',
  // 'kiRUTvgxRGEU': 'tags',
  // '0pWPOTkeJ4ou': 'acf.author_13plus',
  'cCtnKNF62tdD': 'acf.author_firstname',
  // 'TkcWAwJKtA0t': 'acf.author_lastname',
  // 'R5tkVz3rTzyV': 'acf.author_email',
  // 'YyAwGwFFhcv9': 'acf.author_community',
  // 'JsiJT53nZ7hA': 'acf.author_age',
  // 'QXNwuNPOl9Au': 'acf.author_race_ethnicity',
  // 'siMgqnMbaPOD': 'acf.author_gender',
  // 'vzq9hhEpRtB5': 'acf.author_comments',
  // 'ONGanBAnwVcb': 'acf.story_content',
  // 'fDvLg5uTIcol': 'acf.story_audio_url',
  // 'LwSMnEdjg3lo': 'acf.story_city',
  // '25LtGwnYl9m9': 'acf.story_address',
  // 'NHUKT3EzpMEQ': 'acf.story_zip',
  // 'Xpby4jkXPJGo': 'acf.story_private_residence',
  // 'veG6QCVqbLQm': 'acf.story_still_exist',
  // 'OFcWqPxkaqqr': 'acf.story_video_url',
  // 'PCT92ywkggUp': 'acf.images',
  // 'J429I5JhdsSq': 'acf.story_image_url_1',
  // 'L3iAUQOe99tJ': 'acf.story_image_url_2',
  // 'jx7RU0owx19W': 'acf.story_image_url_3',
  // 'fdbfK7ViCL5Q': 'acf.story_image_url_4',
  // '3yp6J4Xx3ABe': 'acf.story_image_url_5',
};